blog/urls.py
from django.urls import path
from .views import render_posts, post_detail


app_name = 'blog'


urlpatterns = [
    path('', render_posts, name='posts'),
    path('<int:post_id>', post_detail, name='post_detail'),
]

webPortafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


from portafolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.db.models.fields import CharField
from django.db.models.fields import TextField
from django.db.models.fields.files import ImageField
from django.db.models.fields import DateTimeField

import datetime


class Post(models.Model):
    title = CharField(max_length=200)
    description = TextField()
    image = ImageField(upload_to="blog/images")
    date_posted = DateTimeField(datetime.date.today())

portafolio/models.py
from django.db import models
from django.db.models.fields import CharField
from django.db.models.fields import TextField
from django.db.models.fields.files import ImageField
from django.db.models.fields import URLField


class Project (models.Model):
    title = CharField(max_length=100)
    description = TextField()
    image = ImageField(upload_to="portafolio/images/")
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post


def render_posts(request):
    posts = Post.objects.all()
    return render(request, 'posts.html', {"posts":posts})


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'post_detail.html', {"post": post})

portafolio/views.py
from django.shortcuts import render
from .models import Project


def home(request):
    projects = Project.objects.all()

    return render(request, 'home.html', {'projects': projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'main.css' %}">

{% block content %}

    <div class="text-center">
        <h2>{{ post.title }}</h2>
        <h3>{{ post.date_posted | date:'F jS Y'}}</h3>

        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid" id="publicationImage">

        <div class="my-4">
            <p>{{ post.description |safe}}</p>
        </div>
    </div>

{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}
<h1>Posts</h1>

{% block content %}
    {% for post in posts %}
        <div class="p-3">
            <div class="card card-body" id="cardPublication">
                <div class="row">
                    <div class="col-3">
                        <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid">
                    </div>
                    <div class="col-9">
                        <h2>{{ post.title }}</h2>
                        <p>{{ post.description |striptags |truncatechars:100 }}</p>
                        <p>{{ post.date_posted |date:'M d Y' |upper}}</p>

                        <a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary ">
                            {{ post.title }}
                        </a>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

portafolio/templates/home.html
{% extends 'layout.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'main.css' %}">

{% block content %}

    <header class="row" id="myInfoSection">
        <div class="col-md-3">
            <img src="{% static 'portfolio/profile.jpg' %}" alt="" class="img-fluid" id="profileImage" style="max-width: 412px; max-height: 360px">
        </div>

        <div class="col-md-8 my-auto" >
            <h1> I am <strong> Hector David Madrid Rivera</strong></h1>
            <h3> I am a Software engineer graduated from de Universidad Veracruzana</h3>
            <p> I have knowledge of Python, Flutter, Java, C++, C#, and Javascript</p>
            <p> I have participated 2 times on the ICPC Programing Contest, one in 2020 and another in 2021</p>
            <p> In the second ICPC my team won the 197 place I was in fifth semester of university</p>
            <a href="{% static 'portfolio/CV.pdf' %}" class="btn btn-primary btn-lg rounded=0 my-3" target="_blank">
                Download CV
            </a>
        </div>
    </header>

    <div class="row my-4 text-center">

        <h3>My most important projects</h3>
        <p> Those are the projects where I worked, most of this are university
            projects, but there are some projects of the real world
        </p>

        {% for project in projects %}

            <div class="col-md-4 p-4" >
                <div class="card card-project" id="cardProject">
                    <img src="{{ project.image.url }}" alt="{{ project.title }}" class="card-img-top" style="max-height: 450px"/>
                    <div class="card-body">
                        <h2>{{ project.title }}</h2>
                        <p>{{ project.description }}</p>

                        {% if project.url %}
                            <a href="{{ project.url }}" class="btn btn-light rounded-0 btn-sm" target="_blank">Link a repositorio</a>
                        {% endif %}
                    </div>
                </div>
            </div>

        {% endfor %}

    </div>

{% endblock %}

portafolio/templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
          rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css' %}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

    <div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="wave"></div>
        <div class="container p-4">
            {% block content %}
            {% endblock %}
        </div>

    </div>

</body>
</html>

portafolio/templates/partials/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark bg-black">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">HDMR</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/CV.pdf'%}" target="_blank">Download CV</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}" >Publications</a>
        </li>
      </ul>
    </div>
  </div>
</nav>